## Importações
### Importando as bibliotecas necessárias

In [ ]:
%pip install -U scikit-learn

:

In [1]:
import pandas as pd
import sklearn as sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

## Lendo os datasets

In [29]:
df_resultado = pd.read_csv("D:/Módulo07/nossosModelos/rod_maquina.csv",low_memory=False)
df_resultado

:

In [3]:
df_rod = pd.read_csv("D:/Módulo07/nossosModelos/df_rod.csv",low_memory=False)
df_rod

In [23]:
# df_resultado.drop(df_resultado.columns[9],axis=1,inplace=True)
df_resultado.head(200)

,KNR,MODELO,COR,MOTOR,ESTACAO,USUARIO,HALLE,FALHA,DATA_x,Unnamed: 9,NAME,ID,STATUS,UNIT,VALUE_ID,VALUE,DATA_y
0,2024-1346277,T-CROSS,K2K2,CWL,PCEQS709,2079860,ROD,Console central Ruído de corpo estranho,5/4/2024 16:50:34,10282126,012001,1,10,NaN,0.0,NaN,2024-03-27 15:49:28
1,2024-1346277,T-CROSS,K2K2,CWL,PCEQS709,2079860,ROD,Console central Ruído de corpo estranho,5/4/2024 16:50:34,10282127,012001,1,10,NaN,NaN,NaN,2024-03-27 15:49:28
2,2024-1346277,T-CROSS,K2K2,CWL,PCEQS709,2079860,ROD,Console central Ruído de corpo estranho,5/4/2024 16:50:34,10282128,012002,1,10,NaN,0.0,NaN,2024-03-27 16:08:24
3,2024-1346277,T-CROSS,K2K2,CWL,PCEQS709,2079860,ROD,Console central Ruído de corpo estranho,5/4/2024 16:50:34,10282129,012002,1,10,NaN,NaN,NaN,2024-03-27 16:08:24
4,2024-1346277,T-CROSS,K2K2,CWL,PCEQS709,2079860,ROD,Console central Ruído de corpo estranho,5/4/2024 16:50:34,10282130,012003,1,10,NaN,0.0,NaN,2024-03-27 16:08:38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2024-1346277,T-CROSS,K2K2,CWL,PCEQS709,2079860,ROD,Console central Ruído de corpo estranho,5/4/2024 16:50:34,10282321,214900,2,10,NaN,NaN,NaN,2024-03-27 14:30:12
196,2024-1346277,T-CROSS,K2K2,CWL,PCEQS709,2079860,ROD,Console central Ruído de corpo estranho,5/4/2024 16:50:34,10282322,215400,2,10,Grad,1.0,0.00 ...,2024-03-27 16:05:37
197,2024-1346277,T-CROSS,K2K2,CWL,PCEQS709,2079860,ROD,Console central Ruído de corpo estranho,5/4/2024 16:50:34,10282323,215400,2,10,Grad,5.0,0.00 ...,2024-03-27 16:05:37
198,2024-1346277,T-CROSS,K2K2,CWL,PCEQS709,2079860,ROD,Console central Ruído de corpo estranho,5/4/2024 16:50:34,10282324,215400,2,10,Grad,9.0,106.00 ...,2024-03-27 16:05:37
199,2024-1346277,T-CROSS,K2K2,CWL,PCEQS709,2079860,ROD,Console central Ruído de corpo estranho,5/4/2024 16:50:34,10282325,215400,2,10,Grad,3.0,92.00 ...,2024-03-27 16:05:37

## Pré Processamento dos dados

### Padronização

Para realizar a padronização dos dados, é preciso codificar as colunas categóricas do dataset, para possibilitar a interpretação pelo modelo. Assim, deve ser feita a transformação desses dados categóricos para numéricos

In [30]:
#Transformando os dados categóricos em númericos
from sklearn.preprocessing import LabelEncoder

leByColumn = {}
columns = ['KNR', 'MODELO', 'COR', 'MOTOR', 'ESTACAO', 'HALLE', 'FALHA', 'DATA_x', 'NAME', 'UNIT', 'VALUE_ID', 'VALUE', 'DATA_y']
for column in columns:
  le = LabelEncoder()
  leByColumn[column] = le
  df_resultado[column] = le.fit_transform(df_resultado[column])

df_resultado

,KNR,MODELO,COR,MOTOR,ESTACAO,USUARIO,HALLE,FALHA,DATA_x,Unnamed: 9,NAME,ID,STATUS,UNIT,VALUE_ID,VALUE,DATA_y
0,0,0,10,0,0,2079860,0,69,1479,10282126,0,1,10,10,0,33185,1016
1,0,0,10,0,0,2079860,0,69,1479,10282127,0,1,10,10,45,33185,1016
2,0,0,10,0,0,2079860,0,69,1479,10282128,1,1,10,10,0,33185,1044
3,0,0,10,0,0,2079860,0,69,1479,10282129,1,1,10,10,45,33185,1044
4,0,0,10,0,0,2079860,0,69,1479,10282130,2,1,10,10,0,33185,1045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1906632,1722,0,0,2,0,2041820,0,110,1236,21463681,272,718,10,10,45,33185,304113
1906633,1722,0,0,2,0,2041820,0,110,1236,21463682,273,718,10,10,45,33185,304113
1906634,1722,0,0,2,0,2041820,0,110,1236,21463683,274,718,10,10,45,33185,304113
1906635,1722,0,0,2,0,2041820,0,110,1236,21463684,275,718,10,10,45,33185,304113
1906636,1722,0,0,2,0,2041820,0,110,1236,21463685,277,718,13,6,44,9578,320706

### Separação do conjunto de testes para teste de features.

In [ ]:
X = df_resultado.drop('STATUS', axis=1)
y = df_resultado['STATUS']

In [32]:
# Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Criação do modelo preditivo

Criação e treinamento do modelo, utilizando random forest para classificação.

In [33]:
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)

In [34]:
# Treinar o modelo com os dados de treinamento
random_forest.fit(X_train, y_train)

In [35]:
# Fazer previsões no conjunto de teste
y_pred = random_forest.predict(X_test)

In [36]:
# Métricas dos modelos de classificação
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score
)

# Calcular acurácia
accuracy = accuracy_score(y_test, y_pred)
print(f"Acurácia: {accuracy}")

# Calcular precisão
precision = precision_score(y_test, y_pred, average='weighted')  # Defina o argumento `average` conforme apropriado
print(f"Precisão: {precision}")

# Calcular sensibilidade (recall)
recall = recall_score(y_test, y_pred, average='weighted')  # Defina o argumento `average` conforme apropriado
print(f"Sensibilidade (Recall): {recall}")

# Calcular F1-score
f1 = f1_score(y_test, y_pred, average='weighted')  # Defina o argumento `average` conforme apropriado
print(f"F1-Score: {f1}")

Acurácia: 0.996360088952293
Precisão: 0.9960079157414826
Sensibilidade (Recall): 0.996360088952293
F1-Score: 0.99590065534183